pipeline:
  hugo:
    image: cbrgm/drone-hugo
    pull: true
    validate: true
    url: https://cloudnativecasts.com/

  docker:
    image: plugins/docker
    repo: cloudnativecasts/website
    secrets: [ docker_username, docker_password ]
    tags:
      - 'latest'
    when:
      branch: master
      event: push

  kubernetes-api:
    image: kubeciio/kubectl:0.2
    kubectl: apply
    templates:
      - kuberentes/certificate.yaml
      - kuberentes/ingress.yml
      - kuberentes/service.yml
      - kuberentes/deployment.yml
    secrets: [ kubeconfig ]
    when:
      branch: master
      event: push
